package common.enums.types;

public enum RequestType {
    REGISTER,
    LOGIN,
    GET_PROFILE,
    UPDATE_PERSONAL,
    UPDATE_CREDENTIALS,

    GET_MEDICAL_CARD,
    CANCEL_APPOINTMENT,
    GET_REFERENCES,
    GET_PRESCRIPTIONS,
    GET_SCHEDULES,
    GET_AVAILABLE_TIMES,
    GET_MEDICAL_CARD_ID,
    ADD_APPOINTMENT,

    GET_APPOINTMENT_HISTORY,
    GET_APPOINTMENT_RECORDS,
    GET_PATIENTS,
    GET_WORKING_SCHEDULE,
    GET_TODAY_APPOINTMENTS,
    UPDATE_APPOINTMENT,

    GET_ALL_USERS,
    GET_ALL_DOCTORS,
    GET_ALL_PATIENTS,
    GET_ALL_APPOINTMENTS,
    ADD_WORK_DAY,
    UPDATE_WORK_DAY,
    DELETE_WORK_DAY,
    ADD_DOCTOR,
    ADD_PATIENT
}